baseURL = "https://nbuehlmann.github.io/soerenberg2026/"
languageCode = "de-CH"
timeZone = "Europe/Zurich"
title = "Sörenberger OL Weekend"
theme = "arcana"
copyright = "© OLV Luzern. 2026"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
disableKinds = ['taxonomy', 'term']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
    [languages.de]
        languageName = "Deutsch"
        languageCode = 'de-CH'
        disabled = false
        weight = 1
    [languages.en]
        languageName = "English"
        languageCode = 'en-US'
        disabled = false
        weight = 2
    [languages.fr]
        languageName = "Français"
        languageCode = 'fr-CH'
        disabled = true
        weight = 3

[taxonomies]
    tag = "tags"

[params]
    description = "Eine responsive Webseiten-Vorlage im Business- und Unternehmensstil."
    show_post_dates = false